name: Deploy Infra

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: test write
        run: |
          echo "I am being called"

      - name: "Az CLI login"
        uses: Azure/login@v2.0.0
        with:
          client-id: "dfsd"
          tenant-id: "sdfsnslknslk"
          subscription-id: "sdlknsdlskn"

          # client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
