name: Deploy Infra

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      destroy:
        required: true
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0

      - name: "Az CLI login"
        uses: Azure/login@v2.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.9.0
        id: app-token
        with:
          app-id: ${{ secrets.TF_MODULE_AUTH_APP_ID }}
          private-key: ${{ secrets.TF_MODULE_AUTH_APP_SECRET }}
          owner: ${{ github.repository_owner }}

      - name: Git Config
        run: git config --global url."https://x-access-token:${{ steps.app-token.outputs.token  }}@github.com".insteadOf ssh://git@github.com

      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -backend-config=backend.tfvars

      - name: Check destroy arg
        id: destroy_arg
        env:
          DESTROY: ${{ inputs.destroy }}
        run: |
          if $DESTROY
          then
            echo "val=-destroy" >> $GITHUB_OUTPUT
          else
            echo "val= " >> $GITHUB_OUTPUT
          fi

      - name: Terraform apply
        id: apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply $DESTROY -var-file=${{ inputs.environment }}.tfvars -auto-approve -input=false -lock=false
